server:
  port: 9601
spring:
  application:
    name: turbine-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
turbine:
  app-config: hystrix-service  #多个的话,隔开  需要收集的服务名称
  clusterNameExpression: "'default'"
  combine-host-port: true #以主机名和端口号来区分服务
