server:
  port: 9201
spring:
  application:
    name: ribbon-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/  #测试启动eureka-service 的 application.yml配置即可

#修改对应服务ribbon负载策略 默认是轮询
#与自定义写代码的方式实现效果一样
#product-service:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

